<a href="https://colab.research.google.com/github/mdzubayereashraf/Pandas/blob/main/Selecting_Rows_and_Columns_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Selection of Coloums**




1.  df['Name'] # single column
2.  df[['Name', 'Age']] # multiple columns

## **`Single column`**

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Titinic /titanic.csv")

df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

## **`Multiple columns`**

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df[['Name','Age', 'Sex','Fare']]

                                                  Name   Age     Sex     Fare
0                              Braund, Mr. Owen Harris  22.0    male   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female  71.2833
2                               Heikkinen, Miss. Laina  26.0  female   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female  53.1000
4                             Allen, Mr. William Henry  35.0    male   8.0500
..                                                 ...   ...     ...      ...
886                              Montvila, Rev. Juozas  27.0    male  13.0000
887                       Graham, Miss. Margaret Edith  19.0  female  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female  23.4500
889                              Behr, Mr. Karl Howell  26.0    male  30.0000
890                                Dooley, Mr. Patrick  32.0    male   7.7500

[891 rows x 4 columns]

# **Selection of Rows**

# **`loc → label based`**
1. df.loc[0] # row with index 0
2. df.loc[0:2, ['Name', 'Age']] #rows 0 to 2, selected cols

# **`iloc → index position based`**
1. df.iloc[0] # first row
2. df.iloc[0:3] # first 3 rows
3. df.iloc[:, 1] # all rows, 2nd col

## **`Selecting any particular row`**

In [ ]:
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
df.loc[17]

PassengerId                              18
Survived                                  1
Pclass                                    2
Name           Williams, Mr. Charles Eugene
Sex                                    male
Age                                     NaN
SibSp                                     0
Parch                                     0
Ticket                               244373
Fare                                   13.0
Cabin                                   NaN
Embarked                                  S
Name: 17, dtype: object

## **`Selecting multiple particular rows from any position `**

In [ ]:
df.loc[4:9]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

## **`Selecting a particular row and a column`**

In [ ]:
df.loc[9,'Name']

'Nasser, Mrs. Nicholas (Adele Achem)'

## **`Selecting multiple particular rows and a column`**

In [ ]:
df.loc[10: 15, 'Name']

10         Sandstrom, Miss. Marguerite Rut
11                Bonnell, Miss. Elizabeth
12          Saundercock, Mr. William Henry
13             Andersson, Mr. Anders Johan
14    Vestrom, Miss. Hulda Amanda Adolfina
15        Hewlett, Mrs. (Mary D Kingcome)
Name: Name, dtype: object

## **`Selecting a particular rows and multiple columns`**

In [ ]:
df.loc[19,['Name','Age','Sex']]

Name    Masselmani, Mrs. Fatima
Age                         NaN
Sex                      female
Name: 19, dtype: object

## **`Selecting multiple particular rows and  columns simultaneously`**

In [ ]:
df.loc[10: 15, ['Name', 'Age']]

                                    Name   Age
10       Sandstrom, Miss. Marguerite Rut   4.0
11              Bonnell, Miss. Elizabeth  58.0
12        Saundercock, Mr. William Henry  20.0
13           Andersson, Mr. Anders Johan  39.0
14  Vestrom, Miss. Hulda Amanda Adolfina  14.0
15      Hewlett, Mrs. (Mary D Kingcome)   55.0

# **`iloc → index position based`**
## **`Selecting a single row by index number`**

In [ ]:
df.iloc[37]

PassengerId                          38
Survived                              0
Pclass                                3
Name           Cann, Mr. Ernest Charles
Sex                                male
Age                                21.0
SibSp                                 0
Parch                                 0
Ticket                       A./5. 2152
Fare                               8.05
Cabin                               NaN
Embarked                              S
Name: 37, dtype: object

## **`Selecting multiple row by index number from any range`**

In [ ]:
df.iloc[26:29]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q

## **`Selecting a single row  and column by index number`**

In [ ]:
df.iloc[43 , 3] # index 3 of column is Name

'Laroche, Miss. Simonne Marie Anne Andree'

## **`Selecting multiple rows and columns  by index number`**

In [ ]:
df.iloc[3:7, 1: 4]

   Survived  Pclass                                          Name
3         1       1  Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                      Allen, Mr. William Henry
5         0       3                              Moran, Mr. James
6         0       1                       McCarthy, Mr. Timothy J